name: dears
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.2
  flutter: 3.24.2

dependencies:
  dio: ^5.4.3+1
  firebase_analytics: ^11.3.0
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  kakao_flutter_sdk_user: ^1.9.6
  logger: ^2.4.0
  retrofit: ^4.1.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.1
  sign_in_with_apple: ^6.1.2
  stomp_dart_client: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.7
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lint: ^2.3.0
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: DearsIcons
      fonts:
        - asset: fonts/DearsIcons.ttf
