name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          cache: true

      - run: flutter pub get

      - run: dart run build_runner build --delete-conflicting-outputs

      - run: flutter analyze
      - run: dart run custom_lint

      - run: flutter test
